### ISSUE TITLE
#include "nss_ndb.h" is missing

### ISSUE THREAD

**Issue by UlasSAYGINIM** [ptrrkssn/nss_ndb#1]
Hi,
#include "nss_ndb.h" is not uploaded. can you check others files too and update the repo?
thanks a lot. have a nice day.

**Comment by ptrrkssn** [comment]
Fixed (and some other fixes too)!

**Comment by UlasSAYGINIM** [comment]
Thank you very much. i missed this event , i am sorry about that.
thank you for your great work.
