### ISSUE TITLE
Freebsd problems to build and create database.

### ISSUE THREAD

**Issue by UlasSAYGINIM** [ptrrkssn/nss_ndb#3]
Hi ,
I tried to build nss_ndb on freebsd 12.1

when i  want to compite it gives error.

cc  -pthread -fPIC -O -g -Wall -DVERSION="\"1.5\""  -DWITH_NSS_NDB=1 -c nss_ndb.c -o nss_ndb.o
ld -ldb --shared  -o nss_ndb.so.1.5 nss_ndb.o
ld: error: unable to find library -ldb
*** Error code 1

Stop.

I deleted LIBARGS=-ldb option in Makefile like this
LIBARGS=
#-ldb

then it compiled like this .
 make install
ld  --shared  -o nss_ndb.so.1.5 nss_ndb.o
cc  -pthread -fPIC -O -g -Wall -DVERSION="\"1.5\""  -DWITH_NSS_NDB=1 -c makendb.c -o makendb.o
cc -g -o makendb makendb.o nss_ndb.o
cc  -pthread -fPIC -O -g -Wall -DVERSION="\"1.5\""  -DWITH_NSS_NDB=1 -c nsstest.c -o nsstest.o
cc -g -o nsstest nsstest.o nss_ndb.o -lpthread -ldl
install -o root -g wheel -m 0755 nss_ndb.so.1.5 /usr/lib && ln -sf nss_ndb.so.1.5 /usr/lib/nss_ndb.so.1
install -o root -g wheel -m 0755 makendb nsstest /usr/bin
install -o root -g wheel -m 0755 ndbsync /usr/sbin
install -o root -g wheel -m 0444 makendb.1 /usr/share/man/man1

I changed nss config options then

I also looked make tests.

 make tests
./nsstest  -C'tesje148:*:11189:100000000:Testkonto Jean-Jacquesmoulis:/home/tesje148:/bin/sh' getpwnam tesje148
./nsstest: Error: getpwnam yielded unexpected result (rc=1)
*** Error code 1

Stop.
make: stopped in /usr/home/installeruser/nss_ndb

Thirdly , database creation problem.

i tried to populate db for nss_ndb and i used that command but it gives error.
I have created /var/db/nss_ndb directory but no luck.

 makendb -T passwd /var/db/nss_ndb/passwd </etc/master.passwd
makendb: /var/db/nss_ndb/passwd/passwd.byuid.db: dbopen: No such file or directory

**Comment by ptrrkssn** [comment]
Thanks for the bug report, it seems the Makefile in the GIT repo was a bit incorrect when it comes to the building part. I've fixed that now (it can build either with the old BerkeleyDB in "libc", or with the ones in port (db4.8, db5 or db6) - and the Makefile was half-left using db5 for some strange reason).

Regarding "make check" I've made some fixes in the Makefile for that too (it used some hard-coded names & data only valid at our site).

Regarding makendb you should use: 
 makendb -T passwd /var/db/nss_ndb </etc/master.passwd

**Comment by UlasSAYGINIM** [comment]
thank you very much for fast response. God bless you! i really like the speed. you are amazing!.

I have used perl script , to create berkeley database , then i am able to use the nss_ndb.
without empty database , i was not working. i didnt use berkeley db before couldnt find to way to create but perl script was good option to do.
While i was setting up perl script, i noticed that there are some modules that need to be installed.
I noted them, if you like it , you may create wiki page for it.

and for perl script , i changed variables in it to connect to database but it didnt connect it.
in order to do it, i used options -D -N.
I was expecting, if i run ndbsync , it will connect to mysql and get users and groups, and saved into default path into /var/db/nss_ndb/  but it didnt without parameters.

in additionally, you may add creating user for nss_ndb mysql database schema.
it can help people.

one question, does perl script , delete old berkeley db, and then create new one,
or it checks there is a db and if there is , perl script is adding new and updated records by checkin them properly?



CREATE DATABASE `myusers` COLLATE 'latin1_general_ci';

CREATE USER 'myusers'@'localhost' IDENTIFIED BY 'superpass123.';

GRANT ALL PRIVILEGES ON myusers.* TO 'myusers'@'localhost';


p5-Config-Tiny-2.24 

cd /usr/ports/devel/p5-Config-Tiny/

make config-recursive

make install clean


p5-match-simple

 cd /usr/ports/devel/p5-match-simple/

make config-recursive

make install clean


cd /usr/ports/devel/p5-Proc-PID-File

 make config-recursive

make install clean

cd /usr/ports/devel/p5-DB_File-Lock

 make config-recursive

make install clean

**Comment by ptrrkssn** [comment]
The perl script does a delta diff/update on the NDB databases comparing current data with data in the MySQL source and uses a lock while updating it. The idea is that it can be run at anytime and cause only a little "slowdown effect" on other processes accessing the data concurrently (there will be some slow down due to the "write lock" being held but it's not too bad I think).

An old version of the script we used here used to create new databases and then move them in place, but that caused problems with other processes accessing the database in a serial way (and holding them open (think setpwent()/getpwent()/endpwent()) and also caused problems with unnecessary writes to the filesystem every time we updated the databases.

(We use a variant of this code in production on our fileservers since 3 years back and mirror our AD database which right now contains some 130,000 users (and an insane amount of groups) - since talking directly to the AD using an LDAP nsswitch module (or using Sambas winbindd) would have been insanely slow).

Thanks for the suggestions btw - I'll work them into the code and release a new "release" in a while. 

I've updated the Makefile a bit more now in order to make it more "compliant". It will by default install stuff into /usr/local now (except for the database and the symbolic link for "nss_ndb.so.1" that must go into /usr/lib or "nsswitch" won't find the module), but to compile and install into /usr/{lib,bin,sbin) just do "make PREFIX=/usr install".

Also made some fixes with the "tests" stuff (see the Makefile or the README).

- Peter

**Comment by ptrrkssn** [comment]
Btw, using the "nsstest" tool you can compare the speed with other "nsswitch" backends.

See the Makefile for details, the "check-nss" targets "t-passwd", "t-group" and "t-other" run the tests via the system "nsswitch" so will test the whole system (not just NDB stuff) "chain" (the modules specified in /etc/nsswitch.conf for passwd/group).
- Peter

**Comment by UlasSAYGINIM** [comment]
you did a lot of things. i will check them tomorrow because i am not well now.
I need to rest, sorry about that but i am very exccited about it.

I have an idea about lock mechanism.
If your database are not updated for same record by concurrent user requests.
I mean, for id 12 at the same time, 100 users goes update request. it is not possible.
but if it is different records , like each user is updating different record with different id.
you may consider to create second database for fast access like copy of main database.
It is like db1 is in memory file system and nss_ndb uses ramdisk cached database to check user records, but not for update and delete or adding new records.
db2 is main db, people are able to add , update , delete the records after each request,
db2 can be synced to db1. It may increase performance better than lock mechanism.
you may think tempfs or redis to cache db1.

i hope it helps.

**Comment by ptrrkssn** [comment]
Yeah, I've been thinking about different ways to improve the locking. One way is to stop using the libc-builtin BerkeleyDB and use DB6 instead - which has much better built-in locking stuff. (The really old libc-builtin BerkeleyDB doesn't really have any good locking).

But in general use the locking is only a problem if the passwd/group data changes very often, which in reality (atleast not in our use case - perhaps a couple of times per day) doesn't happen that often anyway - normal access is using shared (read) locks which doesn't cause blocking.

Another way of improving speed that I've been thinking about is using some kind of shared memory cache and have a "ndbd" daemon that preloads the data into s shared memory segment and then one could get away from all filesystem access completely. However it takes some work to attach to such shared memory segments, populate&traverse it in an efficient way and I'll have to really benchmark stuff to make sure it really improves things. But that's a lot more work...

Or one can test to see if using the standard "nscd" (name services caching daemon) improves speed measurably...

**Comment by UlasSAYGINIM** [comment]
Good morning Peter,
you have very good ideas. i think shared memory idea is great but it will take a lot of time to develop. maybe , you may start other options like nscd daemon, and redis search (new redis search engine) to test the performance firstly then decide to do better with shared mem cache if it is needed or shared memory is a best option you may create later, and you will have certain benchmarks between all options.

I am sending you some links to check it out to get an idea about what to do or what is the others experience, 

nscd seems very good for host dns cache, maybe it will be good for nss_ndb.
it is easy and quick to try.
https://prefetch.net/blog/2011/03/27/configuring-nscd-to-cache-dns-host-lookups/

for the hit rate there is a question on stackexchange.

https://unix.stackexchange.com/questions/97448/how-can-i-improve-nscds-cache-hit-rate

for the redis part,

https://redislabs.com/blog/making-redis-concurrent-with-modules/
https://oss.redislabs.com/redisearch/

These are not about the lock mechanism, you may continue to try to BerkeleyDB and use DB6, 
or any other solution. i will inform you when i find out better solution.
I am not sure redis can solve your locking thing, but i think it might help.
redis can save data when you updated from redis, and you will not lose data because you will be able to save to filesystem when update, delete and adding occurs.

I will also try nscd cache for nss_ndb if it is possible.
if you have dummy username data, you may send it to me. i may use for tests.

have a nice day.

**Comment by UlasSAYGINIM** [comment]
Hi,
I tested new version on new vm.
first i thought it didnt create database files but after checking it on  /var/db/nss_ndb/ folder.
i saw database files. but unfortunately, it says there is no db file after smae command executed 2snd and 3rd times.

I am posting command execution order. i cant import database to nss_ndb db file.
even group file does not work to import it to db. makendb  does not seems working.
i will check other things you created.


root@fbsd12r:/home/opf/nss_ndb # makendb -T passwd /var/db/nss_ndb/passwd </etc/master.passwd
makendb: /var/db/nss_ndb/passwd/passwd.byuid.db: dbopen: No such file or directory
root@fbsd12r:/home/opf/nss_ndb #  makendb -T group /var/db/nss_ndb/group </etc/group
makendb: /var/db/nss_ndb/group/group.bygid.db: dbopen: No such file or directory

root@fbsd12r:/home/opf/nss_ndb # makendb -T passwd /var/db/nss_ndb </etc/master.passwd
makendb: Missing required source file

root@fbsd12r:/home/opf/nss_ndb # makendb -T passwd /var/db/nss_ndb < /etc/passwd
makendb: Missing required source file

root@fbsd12r:/home/opf/nss_ndb # makendb -T group /var/db/nss_ndb/group </etc/group
makendb: /var/db/nss_ndb/group/group.bygid.db: dbopen: No such file or directory

root@fbsd12r:/home/opf/nss_ndb # makendb -T group /var/db/nss_ndb/group < /etc/group
makendb: /var/db/nss_ndb/group/group.bygid.db: dbopen: No such file or directory

after these commands , it seems it created databases but why it gives error for group?

root@fbsd12r:/home/opf/nss_ndb # cd /var/db/nss_ndb/
group.byuser.db   passwd.byname.db  passwd.byuid.db

root@fbsd12r:/home/opf/nss_ndb # cd /var/db/nss_ndb/
root@fbsd12r:/var/db/nss_ndb # ls
group.byuser.db         passwd.byname.db        passwd.byuid.db

**Comment by UlasSAYGINIM** [comment]
make check seems that have problem with group file which is not exist on /var/db/nss_ndb

root@fbsd12r:/home/opf/nss_ndb # make check
PLEASE NOTE:
1. You must have the NDB database files updated with content in /var/db/nss_ndb
2. You should expect 'make tests' to fail for any user not in the NDB.
To solve #2, use 'make TESTUSER=some-user-in-ndb tests'.

make: don't know how to make /var/db/nss_ndb/group.bygid.db. Stop

make: stopped in /usr/home/opf/nss_ndb

**Comment by UlasSAYGINIM** [comment]
I just typed commands respectively and showing you the results.

root@fbsd12r:/home/opf/nss_ndb # make tests
PLEASE NOTE:
1. You must have the NDB database files updated with content in /var/db/nss_ndb
2. You should expect 'make tests' to fail for any user not in the NDB.
To solve #2, use 'make TESTUSER=some-user-in-ndb tests'.

make: don't know how to make /var/db/nss_ndb/group.bygid.db. Stop

make: stopped in /usr/home/opf/nss_ndb

root@fbsd12r:/home/opf/nss_ndb # make TESTUSER=some-user-in-ndb tests
PLEASE NOTE:
1. You must have the NDB database files updated with content in /var/db/nss_ndb
2. You should expect 'make tests' to fail for any user not in the NDB.
To solve #2, use 'make TESTUSER=some-user-in-ndb tests'.

make: don't know how to make /var/db/nss_ndb/group.bygid.db. Stop

make: stopped in /usr/home/opf/nss_ndb

**Comment by UlasSAYGINIM** [comment]
Hi @ptrrkssn ,
I hope you are doing great.
you updated new features also. it is nice!  can i test these bugs? did you fix them?

**Comment by ptrrkssn** [comment]
Just a quick note that I've made a number of fixes to nss_ndb (mostly minor, but a lot of documentation updates, man pages added etc) so there is now a version 1.0.23 here. 

I've also created a FreeBSD "port" (sysutils/nss_ndb) for it that now has been accepted so it'll be easier in the future to install it.

**Comment by UlasSAYGINIM** [comment]
oh my god, i was thinking to tell you to make a port on freebsd :) it is great news! thank you very much @ptrrkssn !
